In [14]:
import numpy as np

In [16]:
mydata = np.arange(20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
matr1 = np.reshape(mydata, (5,4))
print(matr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [19]:
matr2 = np.reshape(mydata, (5,4), "C")
print(matr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [25]:
matr3 = np.reshape(mydata, (5,4), "F")
print(matr3)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [27]:
matr3[2]

array([ 2,  7, 12, 17])

In [31]:
matr3[2][2]

12

In [32]:
matr3[2,2]

12

In [42]:
matr3[:2,2]

array([10, 11])

In [45]:
print(type(matr1))

<class 'numpy.ndarray'>


In [43]:
type(mydata)

numpy.ndarray

In [50]:
l1 = [1,2,3]
l2 = ['a','b','c']
l3 = [True,False,True]

In [51]:
l4 = [l1, l2, l3]
print(l4)

[[1, 2, 3], ['a', 'b', 'c'], [True, False, True]]


In [52]:
l5 = np.array([l1, l2, l3])
print(l5)

[['1' '2' '3']
 ['a' 'b' 'c']
 ['True' 'False' 'True']]


In [54]:
l6 = [1,2,3]
l7 = ['a','b','c','d']
l8 = [True,False]

In [55]:
l9 = np.array([l6, l7, l8])
print(l9)

[list([1, 2, 3]) list(['a', 'b', 'c', 'd']) list([True, False])]


/var/folders/rm/dc_8jr551p94hshqpr_cz_yh0000gp/T/ipykernel_21224/1092853126.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  l9 = np.array([l6, l7, l8])


In [56]:
l9

array([list([1, 2, 3]), list(['a', 'b', 'c', 'd']), list([True, False])],
      dtype=object)

In [62]:
l9[1][2]

'c'

------

In [63]:
dict1 = {'k1':'v1', 'k2':'v2'}

In [64]:
dict1

{'k1': 'v1', 'k2': 'v2'}

In [66]:
dict1['k1']

'v1'