In [1]:
range(5)

range(0, 5)

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [9]:
x = list(range(5))
print(x)

[0, 1, 2, 3, 4]


In [10]:
y = list(range(1,5))
print(y)

[1, 2, 3, 4]


In [15]:
z = list(range(100,500,50))
print(z)

[100, 150, 200, 250, 300, 350, 400, 450]


In [18]:
lis = [x,y,z,"Hello", "world", True]
print(lis)

[[0, 1, 2, 3, 4], [1, 2, 3, 4], [100, 150, 200, 250, 300, 350, 400, 450], 'Hello', 'world', True]


-----

In [19]:
w = ['a', 'b', 'c', 'd', 'e', 'f']

In [20]:
w[0]

'a'

In [21]:
len(w)

6

In [22]:
w[-1]

'f'

In [23]:
#startIndex + endIndex = len

In [24]:
w[2] = 45

In [25]:
w

['a', 'b', 45, 'd', 'e', 'f']

----

In [44]:
s = list(range(10))
print(s)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
s[2:]

[2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
s[:5]

[0, 1, 2, 3, 4]

In [35]:
s[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
s[2:7]

[2, 3, 4, 5, 6]

In [37]:
s[-8:7]

[2, 3, 4, 5, 6]

In [38]:
s[-8:-3]

[2, 3, 4, 5, 6]

In [39]:
s[2:7:2]

[2, 4, 6]

In [46]:
s[::-2]

[9, 7, 5, 3, 1]

In [45]:
s[::2]

[0, 2, 4, 6, 8]

-----

In [47]:
s[2:7:-1]

[]

In [48]:
s[7:2:-1]

[7, 6, 5, 4, 3]

---

In [2]:
t1 = (1,2,3,4)
print(t1)

(1, 2, 3, 4)


In [3]:
t1[0]

1

-----

In [1]:
import numpy as np

In [8]:
np.array(t1)

array([1, 2, 3, 4])

In [6]:
a = np.array(t1)
print(a)

[1 2 3 4]


In [16]:
b = np.array([12, 23.21, 323232, True, "abc"])
print(b)

['12' '23.21' '323232' 'True' 'abc']


In [17]:
c = a[2:4] #view
print(c)

[3 4]


In [18]:
d = a.copy()
print(d)

[1 2 3 4]
